import locale
import re
from locale import format_string, localeconv
from math import floor, log10
from typing import Any, TypeVar
from warnings import deprecated


_NumberT = TypeVar("_NumberT", int, float)


KILOBYTE = pow(2, 10)
MEGABYTE = pow(2, 20)
GIGABYTE = pow(2, 30)
TERABYTE = pow(2, 40)


def can_coerce_to_int(value: Any) -> bool:
    return to_int(value) is not None


def coerce_between(value: _NumberT, min_value: _NumberT, max_value: _NumberT) -> _NumberT:
    if value < min_value:
        return min_value
    if value > max_value:
        return max_value
    return value


def format_file_size(size: int, separator: str = "") -> str:
    if size >= TERABYTE:
        return locale.str(round(size / TERABYTE, 1)) + separator + "T"
    if size >= GIGABYTE:
        return locale.str(round(size / GIGABYTE, 1)) + separator + "G"
    if size >= MEGABYTE:
        return locale.str(round(size / MEGABYTE, 1)) + separator + "M"
    if size >= KILOBYTE:
        return locale.str(round(size / KILOBYTE, 1)) + separator + "K"
    return str(size)


def int_to_string(value: int | None, locale: str, nbsp: bool = False) -> str:
    """
    Formats an integer with locale-specific thousand separators, which are at
    least correct for Swedish and English locales. (Usage of the functions in
    the built-in `locale` package requires you to run setlocale() multiple
    times, which is not thread safe and may be resource heavy, so we don't do
    that.)
    """
    if value is None:
        return ""

    if locale.lower().startswith("sv"):
        separator = " "
    else:
        separator = ","

    if separator == " " and nbsp:
        separator = "&nbsp;"

    # Neat line of code, huh? :)
    # 1. Use absolute value to get rid of minus sign
    # 2. Reverse str(value) in order to group characters from the end
    # 3. Split it by groups of 3 digits
    # 4. Remove empty values generated by re.split()
    # 5. Re-reverse the digits in each group & join them with separator string
    # 6. Re-reverse the order of the groups
    # 7. Add minus sign if value was negative
    return ("-" if value < 0 else "") + separator.join(
        [v[::-1] for v in re.split(r"(\d{3})", str(abs(value))[::-1]) if v][::-1]
    )


def localize_float(
    value: float,
    grouping: bool = True,
    min_decimals: int | None = None,
    max_decimals: int | None = None,
) -> str:
    if max_decimals is None:
        max_decimals = 15

    if min_decimals is not None and min_decimals > max_decimals:
        raise ValueError("min_decimals must be <= max_decimals")
    if 15 < (min_decimals or 0) < 0:
        raise ValueError("min_decimals must be >= 0 and <= 15")
    if 15 < (max_decimals or 0) < 0:
        raise ValueError("max_decimals must be >= 0 and <= 15")

    decimal_separator = localeconv()["decimal_point"]
    ret = format_string("%.*f", (max_decimals, value), grouping=grouping)

    if decimal_separator in ret:
        base, decimals = ret.split(decimal_separator)
        decimals = decimals.rstrip("0").ljust(min_decimals or 0, "0")
        if not decimals:
            return base
        return base + decimal_separator + decimals

    return ret


@deprecated("There's rounded_percentage() instead.")
def percent_rounded(part: int | float, whole: int | float) -> int:
    if not whole:
        return 0
    return round(part / whole * 100)


def roman(n: int) -> str:
    if n % 1:
        raise ValueError("roman(): fractions not allowed")
    if n >= 4000 or n < 0:
        raise ValueError("roman(): value must be >= 0 and < 4000")

    m = {
        1000: "M",
        900: "CM",
        500: "D",
        400: "CD",
        100: "C",
        90: "XC",
        50: "L",
        40: "XL",
        10: "X",
        9: "IX",
        5: "V",
        4: "IV",
        1: "I",
    }
    r = ""

    for k, v in m.items():
        while n >= k:
            r += v
            n -= k

    return r


def round_to_n(x: int | float, n: int) -> int | float:
    """
    Rounds x to n significant digits. If the result is a whole number, it is
    cast to int, otherwise float is returned.
    """
    if x == 0:
        return x
    result = round(x, -int(floor(log10(abs(x)))) + (n - 1))
    return int(result) if not result % 1 else result


def rounded_percentage(part: int | float, whole: int | float, digits: int = 3) -> int | float:
    """
    Percentage rounded to `digits` significant digits. Also division-by-zero
    safe!
    """
    return round_to_n((part / whole) * 100, digits) if whole != 0 else 0


def to_int(value: Any, default: int | None = None) -> int | None:
    """Like int() but returns a default value instead of raising exception."""
    try:
        return int(value)
    except (ValueError, TypeError):
        return default
